all:
  children:
    kvm_hosts1:
      hosts:
        kvm1:
          ansible_host: 127.0.0.1
          ansible_user: admin
          ansible_become: true

        winvm:
           ansible_host: "{{ win_host }}"
           ansible_user: "{{ win_user }}"
           ansible_password: "{{ win_password }}"
           ansible_connection: winrm
           ansible_winrm_transport: "{{ win_transport }}"
           ansible_winrm_scheme: "{{ win_scheme }}"
           ansible_port: "{{ win_port }}"
           ansible_winrm_server_cert_validation: "{{ win_cert_validation }}"
           ansible_become: false

